version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: enzyme-to-json
    versions:
    - 3.6.1
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
